apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "cronjob.fullname" . }}
  labels:
    app: {{ template "cronjob.name" . }}
    chart: {{ template "cronjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule | quote }}
  {{- if .Values.runOnDemandOnly }}
  suspend: true
  {{ else if .Values.suspend }}
  suspend: true
  {{- end}}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  concurrencyPolicy: {{ .Values.concurrency }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        metadata:
          labels:
            app: {{ template "cronjob.name" . }}
            release: {{ .Release.Name }}
            {{- if .Values.runOnDemandOnly }}
            runOnDemandOnly: "true"
            {{- end}}
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        spec:
          {{- if .Values.activeDeadlineSeconds }}
          activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
          {{- end}}
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- if .Values.externalConfig.enabled }}
              volumeMounts:
              - name: {{ template "cronjob.fullname" . }}
                mountPath: {{ .Values.externalConfig.path }}
              {{- end }}
              command:
{{ toYaml .Values.image.command | indent 16 }}
              args:
{{ toYaml .Values.image.args | indent 16 }}
              # Inject (non sensitive) environment variables from the `Values` config.
              env:
              {{- range $key, $val := .Values.nonSensitiveEnvs }}
              - name: {{ $key }}
                value: {{ $val | quote }}
              {{- end}}
              # Inject (sensitive) environment variables from `Values` config, referring
              # them from the related Secret object. This is an extra measure of security
              # to avoid having credentials displayed in plain text in the template file.
              # https://kubernetes.io/docs/concepts/configuration/secret/
              {{- $chartName := include "cronjob.fullname" . -}}
              {{- range $key, $val := .Values.sensitiveEnvs }}
              - name: {{ $key }}
                valueFrom:
                  secretKeyRef:
                    name: {{ $chartName }}-secret
                    key: {{ $key }}
              {{- end}}
              resources:
{{ toYaml .Values.resources | indent 16 }}
          {{- if .Values.externalConfig.enabled }}
          volumes:
            - name: {{ template "cronjob.fullname" . }}
              secret:
                secretName: {{ template "cronjob.fullname" . }}-external-config-secret
          {{- end }}
