apiVersion: v1
name: public-service
description: Helm chart for deploying an instance of a publicly available service on a K8s cluster (via HTTP from outside the cluster).
version: 1.0.9
maintainers:
  - name: heshamMassoud
