name: lint

on: push

jobs:
  lint:
    name: Lint k8s-charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: test/travis/install.sh
      - run: test/travis/lint.sh
